### PR TITLE
Cleanup examples folder

### PR DESCRIPTION
**Pull request by rhohndorf**
* Sort examples into categories
* Give examples more expressive names
* Format examples with black
* Fix pyright type checker complaints
* Remove  settings json files from example folder

### CODE REVIEW

**Comment by rhohndorf** [comment]
Not all examples are working for me yet and I'm pretty sure in two cases that's because of a bug/change in the agent code.
I feel the examples are more useful for newcomers now.
I know the naming of the examples folders is not very pythonic (PEP8) but I went for clarity over conformity here. I can change it though if you don't like it.

**Comment by Maximilian-Winter** [comment]
Thank you for the PR! Yes I changed a lot and I'm currently working on some additional stuff. I will revisit the examples ones I'm finished with what I'm working on.

**Comment by rhohndorf** [comment]
Okay, so what does this mean for this PR. 
* Should I keep working on it ?
* Do you want to commit it in it's current state ?
* Should we close it ?

**Comment by Maximilian-Winter** [comment]
It would be great if you could continue it.

**Comment by Maximilian-Winter** [comment]
I will work with your code and fix any errors you can't fix.

**Comment by rhohndorf** [comment]
Okay, my last problem is parallel function calls expect a function_call_id which doesn't exist in the function call dict

**Comment by rhohndorf** [comment]
image

**Comment by Maximilian-Winter** [comment]
Sorry this was my fault. I have just fixed it back.

**Comment by Maximilian-Winter** [comment]
@rhohndorf I have fixed the parallel function calling error and the generator stuff.

**Comment by rhohndorf** [comment]
Yupp everything works now

**Pull request merged**
